baseURL = 'https://www.caryme.com/'
languageCode = 'en-us'
title = 'Cary Lee'
theme = 'goa'
author = 'Cary Lee'

## Site Settings
[params]
author = "Cary Lee"
intro = "software engineer, classical singer"
description = "Technology leader at [MD Clarity](https://mdclarity.com), [classical tenor](https://caryleetenor.com), alum of Northwestern University. Loves wine, bicycling, public transit, and inclusive theology. Lives in Seattle with his husband, Todd."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "carylee"
instagram = "caryleetenor"
#xing = "<username>"
linkedin = "carylee"
#twitter = "<username>"
facebook = "carylee"
#google = "<username>"
#googlescholar = "<account_id>"
#orcid = "0123-4567-8901-2345"
#stackoverflow = "<username>"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
hackernews = "caryme"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
#steam = "<username>"
#reddit = "<username>"
#snapchat = "<username>"
youtube = "@CaryLee"
#keybase = "<username>"
#twitch = "<username>"
#soundcloud = "<username>"
#tumblr = "<username>"
#strava = "<username>"
#skype = "<username>"
#telegram = "<username>"
#whatsapp = "<username>"
#buymeacoffee = "<username>"
#kaggle = "<username>"
#holopin = "<username>"
email = "carylee@gmail.com"

[params.extra]
copyright = "Â© 2025 Cary Lee"
poweredby = false
displayrssicon = false

[services]
  [services.googleAnalytics]
    ID = 'G-7ZE310E4RS'
